### ISSUE TITLE
In Challenge 31, typing "cat" as requested causes "cat:  no such file or directory"

### ISSUE THREAD

**Issue by Bikeguy64** [KanoComputing/terminal-quest#82] opened 2017-02-28 23:35 UTC
Title says it all.  Looks like this was posted under Chapter 31 in April of 2016.  Is there a fix for this yet?  Is my daughter not following the instructions?  She also typed "cat dairies" as well, but that didn't work either.

**Comment by radujipa** [comment] 2017-03-01 11:22
Hi @Bikeguy64 and thanks for letting us know. 

I've tried to reproduce this on our latest development build, but I wasn't able to - I ran through the entire challenge. Here it is detailed in full:

```
Terminal Quest
Challenge 31


Step 1:

You've arrived in the shed-shop. [...]

$ ls

----------------------------------------

Step 2:

Huh, you can't see Bernard anywhere. [...]

$ cd basement

----------------------------------------

Step 3:

You walked into Bernard's basement. [...]

$ ls

----------------------------------------

Step 4:

You see what looks like another tool and a couple of diaries.

# See what files are in the basement. Not required.
$ ls

$ cat bernards-diary-1

Well done! Look at the other objects.

$ cat bernards-diary-2
$ cat photocopier.sh

Press Enter to continue.

----------------------------------------

Step 5:

Enough wandering. [...]

Press Enter to continue.

----------------------------------------
```

It seems the problem is in `Step 4`. Could you try running `ls` in the `basement`? You should see the three files there: `bernards-diary-1`, `bernards-diary-2`, and `photocopier.sh`.

If the files are not there, then it means something has gone wrong with the game's filesystem and we need to reset it (if this was the case, then it is bug). For this:

1. Exit Terminal Quest
2. Open a Terminal window (either from Dashboard or Classic Mode).
3. Type `rm -rf ~/.linux-story` and hit `Enter`.
4. Launch Terminal Quest and try the challenge again.

**Comment by Bikeguy64** [comment] 2017-03-01 23:51
Thanks.  No bug.  Just a lack of understanding that my daughter and I needed to type in cat followed by the 3 file names listed.  :)

**Comment by radujipa** [comment] 2017-03-02 11:49
Hi @Bikeguy64, glad to hear this was resolved. Hope you and your daughter are enjoying the OS :)

Closing this issue and old one.

**Closed by radujipa** 2017-03-02 11:49 UTC
